### ISSUE TITLE
Local node-red image is not recognized

### ISSUE THREAD

**Issue by rmvpaps** [muka/redzilla#12]
I tried to add a local node-red image to REDZILLA_IMAGENAME in docker-compose.yml and also config.example.yml
REDZILLA_IMAGENAME: mynode-red-docker:v1.0
time="2018-05-01T11:30:08Z" level=error msg="Internal Error: Error response from daemon: pull access denied for mynode-red-docker, repository does not exist or may require 'docker login'"

Is this as designed? Can we change something to get it to use local images? I tried to change my images 
 name to official image's tags using docker tag command but its not picking that up.
Thank you for your help

**Comment by muka** [comment]
If you use compose you can the example yml.

It should work as I used it before. Does a simple docker run works with that image?

**Comment by rmvpaps** [comment]
Yes. Directly running the image works. docker run works. I tried with docker compose also and its coming up.  

Then I pushed the image to docker hub and tried
For public repository it works - I created an instance. I think there is some checking in docker hub for repository name even if image is present locally because after sometime I changed the repository to private and did a docker login in my system. Then I restarted redzilla and tried to create an instance and it failed with same error message.

I tried adding to config.example.yml also but getting same issue there. I tried with image ID instead of name but got same error.

**Comment by muka** [comment]
Thanks for testing,let me check the code then.

If you want to try to fix it an provide a PR it would be very welcome!

sent from my phone

Il gio 3 mag 2018, 06:47 rmvpaps <notifications@github.com> ha scritto:

**Comment by rmvpaps** [comment]
Hi,
I do not have any experience in Go programming. So cant fix it myself.
But looks like, there is no code for checking if existing. It seems to directly call Image pull in line 168 of docker/client.go. If we call docker pull localimage, we get the same error response

```
logrus.Debugf("Pulling image %s if not available", cfg.ImageName)
	_, err = cli.ImagePull(ctx, cfg.ImageName, types.ImagePullOptions{})
	if err != nil {
		return err
	}
```
Maybe something like cli.ImageInspectwithRaw might be useful.
(https://godoc.org/github.com/docker/docker/client#Client.ImageInspectWithRaw)

**Comment by muka** [comment]
Should be fixed now @rmvpaps  @RohanAsmat  Please reopen if it is not!

Thanks

**Comment by RohanAsmat** [comment]
Hi Muka,

Thank you for an update @muka,
Can you please provide detailed steps of how to achieve this, as what I have done and which still doesn't work is as follows:

1. Uncommenting the image name from docker-compose to opny/redzilla 
2. Renaming config.example.yml to config.yml
3. Updating ImageName in config.yml to rohanasmat/node-red-dashboard-plus-nodes:latest which is pulled from docker hub and it contains additional node palette for Node-RED. 
4. Running docker-compose up 

I am getting the following error: 
`
Building redzilla
Step 1/4 : FROM scratch
 ---> 
Step 2/4 : ENV GIN_MODE=release
 ---> Using cache
 ---> 714a5d49dd7e
Step 3/4 : COPY ./redzilla /redzilla
ERROR: Service 'redzilla' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder893982847/redzilla: no such file or directory

`

Please let me know what I might be doing wrong my image contains some Node-RED dashboard nodes etc. 

Best Regards,
Muhammad Rohan Ali Asmat
